# rectangle formation yaml
# global goal setting
# global_goal:
  # swarm_central_pos: {x: 25.0, y: 0.0, z: 1.0}
  # cable_length : 2.0
  # m_load : 2.0
  # Fcable_1 : {x: 0.0, y: 5.1482, z: 9.8}
  # relative_pos_3 : {x: -1.7321, y: -1.0, z: 0.0} 
  # relative_pos_4 : {x: -1.7321, y: 1.0, z: 0.0}
  # relative_pos_5 : {x: 0.0, y: 2.0, z: 0.0}
  # relative_pos_6 : {x: 1.7321, y: 1.0, z: 0.0} 
  # relative_pos_6 : {x: 0, y: 0, z: 0.0} 

# map_size_x          : 70.0
# map_size_y          : 30.0
# map_size_z          : 3.0
optimization:
  weight_obstacle     : 100000.0
  weight_feasibility  : 10000.0
  weight_sqrvariance  : 10000.0
  weight_time         : 80.0
  obstacle_clearance  : 2.0
  load_dist           : 2.0
  max_vel             : 1.0
  max_acc             : 5.0
  load_length         : 1.0
  load_width          : 0.5
  load_height         : 0.5
  load_mass           : 2.0

cable:
  cable_length        : 4.0
  uav_obs_clearance   : 2.0
  uav_swarm_clearance : 2.0
  cable_clearance     : 2.0
  weight_uav_obs      : 0.0
  weight_uav_swarm    : 0.0
  weight_FM_feasibility : 10000.0 
  weight_FM_norm      : 1.0  
  weight_cable_collision: 0.0
  n_coef_iterate : 3

fsm:
  replan_trajectory_time : 0.2   # s, the max time of replanning trajectory